services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=keyboardcat
    healthcheck:
      test: ["CMD", "psql", "-l", "-U", "postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - database_volume:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 4001:3000
    volumes:
      - .:/code
    environment:
      - DB_URI=postgres://postgres:keyboardcat@database/postgres
    command: npm run docker_dev
volumes:
  database_volume: